export interface PresetCompany {
  companyName: string;
  slug: string;
  country: string;
  officialWebsite: string;
  appDeepLink?: string;
  fetchMethod: 'MANUAL' | 'FOREX_API' | 'WISE_API' | 'HTML_SCRAPER';
  scraperKey?: string;
  sourceUrl?: string;
  supportedSendCurrencies: string[];
  supportedRecvCurrencies: string[];
  transferTime?: string;
  isVerified: boolean;
  /** Typical company spread/margin applied on top of market rate (%). 0 = no adjustment. */
  rateSpreadPercent?: number;
}

export const PRESET_COMPANIES: PresetCompany[] = [

  // ── Korea-based remittance services ──────────────────────────────────────────

  {
    companyName: 'Wise (TransferWise)',
    slug: 'wise',
    country: 'GB',
    officialWebsite: 'https://wise.com',
    appDeepLink: 'wise://',
    fetchMethod: 'WISE_API',
    scraperKey: 'wise',
    sourceUrl: 'https://wise.com/rates/live',
    supportedSendCurrencies: ['KRW', 'USD', 'EUR', 'GBP', 'JPY'],
    supportedRecvCurrencies: ['USD', 'EUR', 'GBP', 'PHP', 'BDT', 'PKR', 'INR', 'NPR', 'VND', 'MMK'],
    transferTime: '1-2 business days',
    isVerified: true,
  },
  {
    companyName: 'Hanpass (한패스)',
    slug: 'hanpass',
    country: 'KR',
    officialWebsite: 'https://www.hanpass.com',
    appDeepLink: 'hanpass://',
    fetchMethod: 'FOREX_API',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'NPR', 'VND', 'INR', 'PKR', 'MMK', 'IDR', 'THB', 'USD', 'CNY', 'MYR', 'KHR', 'LKR'],
    transferTime: 'Same day',
    isVerified: true,
    rateSpreadPercent: 1.2,
  },
  {
    companyName: 'JRF (제이알에프)',
    slug: 'jrf',
    country: 'KR',
    officialWebsite: 'https://www.jrf.co.kr',
    appDeepLink: 'jrfkorea://',
    fetchMethod: 'FOREX_API',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'NPR', 'VND', 'INR', 'PKR', 'MMK', 'IDR', 'USD', 'JPY', 'CNY'],
    transferTime: 'Same day',
    isVerified: true,
    rateSpreadPercent: 1.8,
  },
  {
    companyName: 'Gmoney Korea (지머니코리아)',
    slug: 'gmoney-korea',
    country: 'KR',
    officialWebsite: 'https://www.gmoneytrans.com',
    appDeepLink: 'gmoneytrans://',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['PHP', 'USD', 'CNY', 'VND', 'THB', 'IDR', 'MMK', 'KHR'],
    transferTime: 'Same day',
    isVerified: true,
    rateSpreadPercent: 0,
  },
  {
    companyName: 'GME Remit (지엠이송금)',
    slug: 'gme-remit',
    country: 'KR',
    officialWebsite: 'https://www.gmeremit.com',
    appDeepLink: 'gmeremit://',
    fetchMethod: 'FOREX_API',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['PHP', 'USD', 'BDT', 'NPR', 'VND', 'INR', 'PKR', 'MMK'],
    transferTime: 'Same day',
    isVerified: true,
    rateSpreadPercent: 1.3,
  },
  {
    companyName: 'Sentbe (센트비)',
    slug: 'sentbe',
    country: 'KR',
    officialWebsite: 'https://www.sentbe.com',
    appDeepLink: 'sentbe://',
    fetchMethod: 'FOREX_API',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['PHP', 'USD', 'VND', 'THB', 'IDR', 'CNY', 'BDT', 'NPR', 'PKR'],
    transferTime: '1-3 hours',
    isVerified: true,
    rateSpreadPercent: 0.8,
  },
  {
    companyName: 'E9Pay (이나인페이)',
    slug: 'e9pay',
    country: 'KR',
    officialWebsite: 'https://www.e9pay.co.kr',
    appDeepLink: 'e9pay://',
    fetchMethod: 'FOREX_API',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['PHP', 'USD', 'VND', 'CNY', 'THB', 'IDR'],
    transferTime: 'Same day',
    isVerified: true,
    rateSpreadPercent: 1.4,
  },
  {
    companyName: 'Hibiki (하이비키)',
    slug: 'hibiki',
    country: 'KR',
    officialWebsite: 'https://www.hibiki.co.kr',
    appDeepLink: 'hibiki://',
    fetchMethod: 'FOREX_API',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['JPY', 'PHP', 'VND', 'USD', 'CNY', 'THB'],
    transferTime: 'Same day',
    isVerified: true,
    rateSpreadPercent: 1.5,
  },
  {
    companyName: 'Narabi (나라비)',
    slug: 'narabi',
    country: 'KR',
    officialWebsite: 'https://www.narabi.co.kr',
    fetchMethod: 'FOREX_API',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'NPR', 'VND', 'INR', 'PKR', 'MMK', 'USD'],
    transferTime: 'Same day',
    isVerified: false,
    rateSpreadPercent: 1.8,
  },
  {
    companyName: 'Coinone Transfer (코인원트랜스퍼)',
    slug: 'coinone-transfer',
    country: 'KR',
    officialWebsite: 'https://transfer.coinone.co.kr',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['PHP', 'VND', 'THB', 'IDR', 'USD', 'CNY', 'BDT', 'NPR', 'PKR', 'MMK'],
    transferTime: 'Within hours',
    isVerified: true,
  },
  {
    companyName: '365pay (삼육오페이)',
    slug: '365pay',
    country: 'KR',
    officialWebsite: 'https://www.365pay.co.kr',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'NPR', 'VND', 'PKR', 'MMK', 'USD'],
    transferTime: 'Same day',
    isVerified: false,
  },
  {
    companyName: 'Moneytree Korea (머니트리)',
    slug: 'moneytree-korea',
    country: 'KR',
    officialWebsite: 'https://www.moneytree.co.kr',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'NPR', 'VND', 'MMK', 'USD'],
    transferTime: 'Same day',
    isVerified: false,
  },
  {
    companyName: 'KEB Hana Bank Remittance',
    slug: 'keb-hana',
    country: 'KR',
    officialWebsite: 'https://www.kebhana.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['USD', 'EUR', 'JPY', 'GBP', 'CNY', 'HKD', 'PHP', 'VND', 'THB'],
    transferTime: '1 business day',
    isVerified: true,
  },
  {
    companyName: 'Woori Bank WON Remittance',
    slug: 'woori-won',
    country: 'KR',
    officialWebsite: 'https://www.wooribank.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['USD', 'PHP', 'VND', 'CNY', 'JPY', 'BDT', 'NPR'],
    transferTime: '1 business day',
    isVerified: true,
  },
  {
    companyName: 'KB Kookmin Bank Remittance',
    slug: 'kb-kookmin',
    country: 'KR',
    officialWebsite: 'https://www.kbstar.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['USD', 'EUR', 'JPY', 'CNY', 'PHP', 'VND', 'USD'],
    transferTime: '1 business day',
    isVerified: true,
  },
  {
    companyName: 'Shinhan Bank Remittance',
    slug: 'shinhan-bank',
    country: 'KR',
    officialWebsite: 'https://www.shinhanbank.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['USD', 'EUR', 'JPY', 'CNY', 'PHP', 'VND', 'BDT', 'NPR'],
    transferTime: '1 business day',
    isVerified: true,
  },
  {
    companyName: 'IBK Bank Remittance (기업은행)',
    slug: 'ibk-bank',
    country: 'KR',
    officialWebsite: 'https://www.ibk.co.kr',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['USD', 'CNY', 'PHP', 'VND', 'BDT', 'NPR', 'PKR', 'MMK'],
    transferTime: '1 business day',
    isVerified: true,
  },
  {
    companyName: 'NH Nonghyup Bank Remittance',
    slug: 'nh-bank',
    country: 'KR',
    officialWebsite: 'https://www.nonghyup.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['USD', 'EUR', 'JPY', 'CNY', 'PHP', 'VND'],
    transferTime: '1 business day',
    isVerified: true,
  },
  {
    companyName: 'KakaoBank International Transfer',
    slug: 'kakaobank',
    country: 'KR',
    officialWebsite: 'https://www.kakaobank.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['USD', 'EUR', 'JPY', 'CNY', 'PHP', 'VND', 'THB'],
    transferTime: '1-2 business days',
    isVerified: true,
  },
  {
    companyName: 'Toss International Transfer (토스)',
    slug: 'toss',
    country: 'KR',
    officialWebsite: 'https://toss.im',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['USD', 'EUR', 'JPY', 'CNY', 'PHP', 'VND', 'THB', 'USD'],
    transferTime: '1-2 business days',
    isVerified: true,
  },

  // ── Global remittance services ────────────────────────────────────────────────

  {
    companyName: 'Western Union',
    slug: 'western-union',
    country: 'US',
    officialWebsite: 'https://www.westernunion.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD'],
    supportedRecvCurrencies: ['USD', 'PHP', 'VND', 'BDT', 'NPR', 'PKR', 'INR', 'MMK', 'IDR', 'THB', 'EUR', 'GBP'],
    transferTime: 'Minutes',
    isVerified: true,
  },
  {
    companyName: 'MoneyGram',
    slug: 'moneygram',
    country: 'US',
    officialWebsite: 'https://www.moneygram.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD'],
    supportedRecvCurrencies: ['USD', 'PHP', 'VND', 'BDT', 'NPR', 'PKR', 'INR', 'MMK', 'EUR', 'GBP'],
    transferTime: 'Minutes',
    isVerified: true,
  },
  {
    companyName: 'Remitly',
    slug: 'remitly',
    country: 'US',
    officialWebsite: 'https://www.remitly.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD'],
    supportedRecvCurrencies: ['PHP', 'INR', 'BDT', 'PKR', 'NPR', 'VND', 'MMK', 'IDR', 'LKR', 'USD'],
    transferTime: '3-5 business days',
    isVerified: true,
  },
  {
    companyName: 'WorldRemit',
    slug: 'worldremit',
    country: 'GB',
    officialWebsite: 'https://www.worldremit.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD', 'GBP'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'NPR', 'VND', 'INR', 'PKR', 'MMK', 'IDR', 'THB', 'USD', 'GBP', 'EUR'],
    transferTime: 'Minutes to hours',
    isVerified: true,
  },
  {
    companyName: 'Ria Money Transfer',
    slug: 'ria',
    country: 'US',
    officialWebsite: 'https://www.riamoneytransfer.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'NPR', 'VND', 'INR', 'PKR', 'MMK', 'USD', 'EUR'],
    transferTime: 'Minutes to 1 day',
    isVerified: true,
  },
  {
    companyName: 'PaySend',
    slug: 'paysend',
    country: 'GB',
    officialWebsite: 'https://paysend.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD', 'EUR'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'PKR', 'INR', 'NPR', 'VND', 'USD', 'EUR', 'GBP'],
    transferTime: '1-3 business days',
    isVerified: true,
  },
  {
    companyName: 'TransferGo',
    slug: 'transfergo',
    country: 'GB',
    officialWebsite: 'https://www.transfergo.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD', 'EUR', 'GBP'],
    supportedRecvCurrencies: ['USD', 'EUR', 'GBP', 'PHP', 'INR', 'PKR', 'BDT', 'VND'],
    transferTime: '30 min to 1 day',
    isVerified: true,
  },
  {
    companyName: 'InstaReM (Nium)',
    slug: 'instarem',
    country: 'SG',
    officialWebsite: 'https://www.instarem.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD', 'SGD'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'NPR', 'INR', 'PKR', 'VND', 'MMK', 'IDR', 'THB', 'MYR', 'USD'],
    transferTime: '1-2 business days',
    isVerified: true,
  },
  {
    companyName: 'OFX',
    slug: 'ofx',
    country: 'AU',
    officialWebsite: 'https://www.ofx.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD', 'AUD'],
    supportedRecvCurrencies: ['USD', 'EUR', 'GBP', 'AUD', 'JPY', 'CNY', 'HKD', 'PHP', 'INR'],
    transferTime: '1-2 business days',
    isVerified: true,
  },
  {
    companyName: 'Revolut',
    slug: 'revolut',
    country: 'GB',
    officialWebsite: 'https://www.revolut.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD', 'EUR', 'GBP'],
    supportedRecvCurrencies: ['USD', 'EUR', 'GBP', 'JPY', 'CNY', 'PHP', 'INR', 'BDT', 'VND', 'THB', 'IDR', 'MYR'],
    transferTime: 'Instant to 1 day',
    isVerified: true,
  },
  {
    companyName: 'Xoom (PayPal)',
    slug: 'xoom',
    country: 'US',
    officialWebsite: 'https://www.xoom.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD'],
    supportedRecvCurrencies: ['PHP', 'INR', 'BDT', 'PKR', 'NPR', 'VND', 'USD', 'EUR'],
    transferTime: 'Minutes to hours',
    isVerified: true,
  },
  {
    companyName: 'Skrill',
    slug: 'skrill',
    country: 'GB',
    officialWebsite: 'https://www.skrill.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD', 'EUR'],
    supportedRecvCurrencies: ['USD', 'EUR', 'GBP', 'PHP', 'INR', 'PKR', 'BDT', 'VND'],
    transferTime: '1-2 business days',
    isVerified: true,
  },
  {
    companyName: 'Currencies Direct',
    slug: 'currencies-direct',
    country: 'GB',
    officialWebsite: 'https://www.currenciesdirect.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD', 'EUR', 'GBP'],
    supportedRecvCurrencies: ['USD', 'EUR', 'GBP', 'JPY', 'CNY', 'AUD', 'CAD', 'HKD'],
    transferTime: '1-2 business days',
    isVerified: true,
  },
  {
    companyName: 'TorFX',
    slug: 'torfx',
    country: 'GB',
    officialWebsite: 'https://www.torfx.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD', 'EUR', 'GBP'],
    supportedRecvCurrencies: ['USD', 'EUR', 'GBP', 'AUD', 'CAD', 'JPY', 'CHF', 'HKD', 'NZD'],
    transferTime: '1-2 business days',
    isVerified: true,
  },
  {
    companyName: 'Flywire',
    slug: 'flywire',
    country: 'US',
    officialWebsite: 'https://www.flywire.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD'],
    supportedRecvCurrencies: ['USD', 'EUR', 'GBP', 'CNY', 'JPY', 'AUD', 'CAD'],
    transferTime: '1-3 business days',
    isVerified: true,
  },
  {
    companyName: 'Azimo',
    slug: 'azimo',
    country: 'GB',
    officialWebsite: 'https://azimo.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD', 'EUR', 'GBP'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'NPR', 'PKR', 'INR', 'VND', 'USD', 'EUR', 'GBP'],
    transferTime: '1-2 business days',
    isVerified: true,
  },
  {
    companyName: 'DBS Remit',
    slug: 'dbs-remit',
    country: 'SG',
    officialWebsite: 'https://www.dbs.com.sg/remit',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'SGD', 'USD'],
    supportedRecvCurrencies: ['PHP', 'INR', 'BDT', 'PKR', 'VND', 'IDR', 'THB', 'MYR', 'USD', 'CNY'],
    transferTime: 'Same day to 1 day',
    isVerified: true,
  },

  // ── Japan-Korea corridor ──────────────────────────────────────────────────────

  {
    companyName: 'SBI Remit (Japan)',
    slug: 'sbi-remit',
    country: 'JP',
    officialWebsite: 'https://www.sbiremit.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['JPY', 'KRW'],
    supportedRecvCurrencies: ['PHP', 'VND', 'INR', 'BDT', 'NPR', 'PKR', 'MMK', 'USD'],
    transferTime: '1-2 business days',
    isVerified: true,
  },
  {
    companyName: 'GMO Remit (Japan)',
    slug: 'gmo-remit',
    country: 'JP',
    officialWebsite: 'https://www.gmo-remit.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['JPY', 'KRW'],
    supportedRecvCurrencies: ['PHP', 'VND', 'INR', 'BDT', 'PKR', 'USD'],
    transferTime: '1-2 business days',
    isVerified: true,
  },

  // ── Middle East / Gulf corridor ───────────────────────────────────────────────

  {
    companyName: 'Al Ansari Exchange',
    slug: 'al-ansari',
    country: 'AE',
    officialWebsite: 'https://www.alansariexchange.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['AED', 'USD'],
    supportedRecvCurrencies: ['PHP', 'INR', 'PKR', 'BDT', 'NPR', 'LKR', 'VND', 'USD'],
    transferTime: 'Same day',
    isVerified: true,
  },
  {
    companyName: 'UAE Exchange',
    slug: 'uae-exchange',
    country: 'AE',
    officialWebsite: 'https://www.uaeexchange.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['AED', 'USD'],
    supportedRecvCurrencies: ['PHP', 'INR', 'PKR', 'BDT', 'NPR', 'LKR', 'VND', 'MMK', 'USD'],
    transferTime: 'Same day',
    isVerified: true,
  },

  // ── Australia / New Zealand corridor ─────────────────────────────────────────

  {
    companyName: 'OziRemit',
    slug: 'oziremit',
    country: 'AU',
    officialWebsite: 'https://www.oziremit.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['AUD', 'KRW'],
    supportedRecvCurrencies: ['PHP', 'INR', 'BDT', 'NPR', 'PKR', 'VND', 'USD'],
    transferTime: '1-2 business days',
    isVerified: false,
  },
  {
    companyName: 'TorchRemit',
    slug: 'torchremit',
    country: 'AU',
    officialWebsite: 'https://www.torchremit.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['AUD', 'KRW'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'NPR', 'INR', 'PKR', 'USD'],
    transferTime: '1-2 business days',
    isVerified: false,
  },

  // ── Additional Korea & global companies ───────────────────────────────────────

  {
    companyName: 'Cross Remit (크로스레밋)',
    slug: 'cross-remit',
    country: 'KR',
    officialWebsite: 'https://www.crossremit.co.kr',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'NPR', 'VND', 'INR', 'PKR', 'MMK', 'IDR', 'USD'],
    transferTime: 'Same day',
    isVerified: false,
  },
  {
    companyName: 'IME Korea (아이엠이)',
    slug: 'ime-korea',
    country: 'KR',
    officialWebsite: 'https://www.imekorea.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['NPR', 'INR', 'BDT', 'PHP', 'VND', 'PKR', 'USD'],
    transferTime: 'Same day',
    isVerified: false,
  },
  {
    companyName: 'Korea Post Remittance (우체국 국제환)',
    slug: 'korea-post',
    country: 'KR',
    officialWebsite: 'https://www.epost.go.kr',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW'],
    supportedRecvCurrencies: ['USD', 'EUR', 'JPY', 'CNY', 'GBP', 'HKD', 'PHP', 'VND'],
    transferTime: '1-3 business days',
    isVerified: true,
  },
  {
    companyName: 'iRemit',
    slug: 'iremit',
    country: 'PH',
    officialWebsite: 'https://www.iremit.com.ph',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['USD', 'KRW', 'JPY'],
    supportedRecvCurrencies: ['PHP', 'USD'],
    transferTime: 'Same day',
    isVerified: true,
  },
  {
    companyName: 'Cebuana Lhuillier',
    slug: 'cebuana-lhuillier',
    country: 'PH',
    officialWebsite: 'https://www.cebuanalhuillier.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['USD', 'KRW'],
    supportedRecvCurrencies: ['PHP', 'USD'],
    transferTime: 'Minutes',
    isVerified: true,
  },
  {
    companyName: 'M Lhuillier',
    slug: 'm-lhuillier',
    country: 'PH',
    officialWebsite: 'https://www.mlhuillier.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['USD', 'KRW'],
    supportedRecvCurrencies: ['PHP', 'USD'],
    transferTime: 'Minutes',
    isVerified: true,
  },
  {
    companyName: 'bKash (Bangladesh)',
    slug: 'bkash',
    country: 'BD',
    officialWebsite: 'https://www.bkash.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['USD', 'KRW'],
    supportedRecvCurrencies: ['BDT'],
    transferTime: 'Minutes',
    isVerified: true,
  },
  {
    companyName: 'Nagad (Bangladesh)',
    slug: 'nagad',
    country: 'BD',
    officialWebsite: 'https://nagad.com.bd',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['USD', 'KRW'],
    supportedRecvCurrencies: ['BDT'],
    transferTime: 'Minutes',
    isVerified: false,
  },
  {
    companyName: 'eSewa (Nepal)',
    slug: 'esewa',
    country: 'NP',
    officialWebsite: 'https://esewa.com.np',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['USD', 'KRW'],
    supportedRecvCurrencies: ['NPR'],
    transferTime: 'Minutes',
    isVerified: true,
  },
  {
    companyName: 'GCash (Philippines)',
    slug: 'gcash',
    country: 'PH',
    officialWebsite: 'https://www.gcash.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['USD', 'KRW'],
    supportedRecvCurrencies: ['PHP'],
    transferTime: 'Minutes',
    isVerified: true,
  },
  {
    companyName: 'Maya / PayMaya (Philippines)',
    slug: 'maya',
    country: 'PH',
    officialWebsite: 'https://www.maya.ph',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['USD', 'KRW'],
    supportedRecvCurrencies: ['PHP'],
    transferTime: 'Minutes',
    isVerified: true,
  },
  {
    companyName: 'Easypaisa (Pakistan)',
    slug: 'easypaisa',
    country: 'PK',
    officialWebsite: 'https://www.easypaisa.com.pk',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['USD', 'KRW'],
    supportedRecvCurrencies: ['PKR'],
    transferTime: 'Minutes',
    isVerified: true,
  },
  {
    companyName: 'JazzCash (Pakistan)',
    slug: 'jazzcash',
    country: 'PK',
    officialWebsite: 'https://www.jazzcash.com.pk',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['USD', 'KRW'],
    supportedRecvCurrencies: ['PKR'],
    transferTime: 'Minutes',
    isVerified: false,
  },
  {
    companyName: 'Small World Money Transfer',
    slug: 'small-world',
    country: 'GB',
    officialWebsite: 'https://www.smallworldfs.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD', 'GBP', 'EUR'],
    supportedRecvCurrencies: ['PHP', 'BDT', 'NPR', 'PKR', 'INR', 'VND', 'USD', 'EUR', 'GBP'],
    transferTime: '1-2 business days',
    isVerified: true,
  },
  {
    companyName: 'Pangea Money Transfer',
    slug: 'pangea',
    country: 'US',
    officialWebsite: 'https://www.pangea.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['USD', 'KRW'],
    supportedRecvCurrencies: ['PHP', 'INR', 'BDT', 'PKR', 'VND', 'USD'],
    transferTime: '1-2 business days',
    isVerified: true,
  },
  {
    companyName: 'CurrencyFair',
    slug: 'currencyfair',
    country: 'IE',
    officialWebsite: 'https://www.currencyfair.com',
    fetchMethod: 'MANUAL',
    supportedSendCurrencies: ['KRW', 'USD', 'EUR', 'GBP'],
    supportedRecvCurrencies: ['USD', 'EUR', 'GBP', 'AUD', 'CAD', 'JPY', 'NZD', 'CHF'],
    transferTime: '1-2 business days',
    isVerified: true,
  },
];

export const SUPPORTED_CURRENCIES = [
  { code: 'KRW', name: 'Korean Won', flag: '🇰🇷' },
  { code: 'USD', name: 'US Dollar', flag: '🇺🇸' },
  { code: 'PHP', name: 'Philippine Peso', flag: '🇵🇭' },
  { code: 'BDT', name: 'Bangladeshi Taka', flag: '🇧🇩' },
  { code: 'NPR', name: 'Nepalese Rupee', flag: '🇳🇵' },
  { code: 'VND', name: 'Vietnamese Dong', flag: '🇻🇳' },
  { code: 'INR', name: 'Indian Rupee', flag: '🇮🇳' },
  { code: 'PKR', name: 'Pakistani Rupee', flag: '🇵🇰' },
  { code: 'MMK', name: 'Myanmar Kyat', flag: '🇲🇲' },
  { code: 'IDR', name: 'Indonesian Rupiah', flag: '🇮🇩' },
  { code: 'THB', name: 'Thai Baht', flag: '🇹🇭' },
  { code: 'CNY', name: 'Chinese Yuan', flag: '🇨🇳' },
  { code: 'JPY', name: 'Japanese Yen', flag: '🇯🇵' },
  { code: 'EUR', name: 'Euro', flag: '🇪🇺' },
  { code: 'GBP', name: 'British Pound', flag: '🇬🇧' },
  { code: 'HKD', name: 'Hong Kong Dollar', flag: '🇭🇰' },
  { code: 'KHR', name: 'Cambodian Riel', flag: '🇰🇭' },
];
